[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "python3Packages.virtualenv"]

[phases.install]
cmds = [
  "virtualenv /opt/venv",
  "/opt/venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/uvicorn app:app --host 0.0.0.0 --port $PORT"
